http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: '*'
    paths: 
      - '/ip'
  riotapi:
    host: '*'
    paths:
      - '/lol/*'
  testapi:
    host: '*'
    paths:
      - '/test/*'
  authapi:
    host: '*'
    paths:
      - '/auth/*'

serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  riotapi:
    url: https://kr.api.riotgames.com
  testservice:
    url: http://localhost:8001
  authservice:
    url: http://localhost:8002
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
  - request-transformer
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - key-auth:
      - proxy:
        - action:
            serviceEndpoint: httpbin 
            changeOrigin: true

  riot_pipeline:
    apiEndpoints:
      - riotapi
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      #- key-auth:
      - proxy:
        - action:
            serviceEndpoint: riotapi 
            changeOrigin: true
  testapi_pipepline:
    apiEndpoints:
      - testapi
    policies:
      #- key-auth:
      -
        jwt:
          action:
            secretOrPublicKeyFile: ../public.pem
            secretOrPrivateKeyFile: ../private.pem
            checkCredentialExistence: false
      -
        request-transformer:
          action:
            body:
              add:
                user: req.user
      - proxy:
        - action:
            serviceEndpoint: testservice 
            changeOrigin: true
  auth_pipeline:
    apiEndpoints:
      - authapi
    policies:
      - cors:
        - action:
            origin: "*"
            methods: '*'
            credentials: true
          
      - proxy:
        - action:
            serviceEndpoint: authservice 
            changeOrigin: true
